name: Build Image Tag
on:  
  push:
    tags:
      - '*'
jobs:
  deploy-staging:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: asia.gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#      - name: Build and push
#        id: docker_build
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          push: true
#          tags: asia.gcr.io/theta-topic-392/upload:latest